heavy_hitter:
	g++ heavy_hitter_src.cpp -lpcap -o heavy_hitter_src -std=c++0x -O3
heavy_hitter_qre_parallel:
	g++ heavy_hitter_para_test.cpp -lpcap -lpthread -o heavy_hitter_src_qre_parallel -std=c++0x -O3
heavy_hitter_qre:
	g++ heavy_hitter_src_qre.cpp -lpcap -o heavy_hitter_src_qre -std=c++0x -O3
superspreader:
	g++ superspreader_baseline.cpp -lpcap -o superspreader -std=c++11 -O3
superspreader_qre:
	g++ superspreader_qre.cpp -lpcap -o superspreader_qre -std=c++11 -O3
entropy:
	g++ entropy_baseline.cpp -lpcap -o entropy -std=c++0x -O3
entropy_qre:
	g++ entropy_qre.cpp -lpcap -o entropy_qre -std=c++0x -O3



