heavy_hitter:
	g++ heavy_hitter_src_baseline.cpp main.cpp -lpcap -o heavy_hitter_src -std=c++0x -O3
heavy_hitter_qre:
	g++ heavy_hitter_src_qre.cpp main.cpp -lpcap -o heavy_hitter_src_qre -std=c++0x -O3
heavy_hitter_qre_parallel:
	g++ heavy_hitter_src_qre_parallel.cpp -lpcap -lpthread -o heavy_hitter_src_qre_parallel -std=c++0x -O3
heavy_hitter_qre_parallel2:
	g++ heavy_hitter_src_qre_parallel2.cpp -lpcap -lpthread -o heavy_hitter_src_qre_parallel2 -std=c++0x -O3
heavy_hitter_qre_parallel3:
	g++ heavy_hitter_src_qre_parallel3.cpp -lpcap -lpthread -o heavy_hitter_src_qre_parallel3 -std=c++0x -O3
heavy_hitter_qre_parallel4:
	g++ heavy_hitter_src_qre_parallel4.cpp -lpcap -lpthread -o heavy_hitter_src_qre_parallel4 -std=c++0x -O3
heavy_hitter_qre_simple_parallel:
	g++ heavy_hitter_para_test.cpp -lpcap -lpthread -o heavy_hitter_src_qre_parallel -std=c++0x -O3
superspreader:
	g++ superspreader_baseline.cpp main.cpp -lpcap -o superspreader -std=c++0x -O3
superspreader_qre:
	g++ superspreader_qre.cpp main.cpp -lpcap -o superspreader_qre -std=c++0x -O3
superspreader_qre_parallel:
	g++ superspreader_qre_parallel2.cpp main_parallel.cpp -lpcap -lpthread -o superspreader_qre_parallel -std=c++0x -O3

entropy:
	g++ entropy_baseline.cpp main.cpp -lpcap -o entropy -std=c++0x -O3
entropy_qre:
	g++ entropy_qre.cpp main.cpp -lpcap -o entropy_qre -std=c++0x -O3
syn_flood:
	g++ syn_flood_baseline.cpp main.cpp -lpcap -o syn_flood -std=c++0x -O3
syn_flood_qre:
	g++ syn_flood_qre.cpp main.cpp -lpcap -o syn_flood_qre -std=c++0x -O3
syn_flood_qre_parallel:
	g++ syn_flood_qre_parallel.cpp main_parallel.cpp -lpcap -lpthread -o syn_flood_qre_parallel -std=c++0x -O3
flow_num_qre:
	g++ flow_num_qre.cpp main.cpp -lpcap -o flow_num_qre -std=c++0x -O3
flow_num:
	g++ flow_num_baseline.cpp main.cpp -lpcap -o flow_num -std=c++0x -O3
flow_num_parallel:
	g++ flow_num_qre_parallel.cpp main_parallel.cpp -lpcap -lpthread -o flow_num_parallel -std=c++0x -O3
stat:
	g++ main.cpp stat.cpp -lpcap -o stat -std=c++0x -O3
  







